name: GitHub CI

on:
  push:
    branches:
      - master
    tags:
      - "v*"
  pull_request:
    branches:
      - master
  release:
    types:
      - released
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    strategy:
      matrix:
        platform: [netframework, net-x86, net-x64]
        include:
          - platform: netframework
            package-name: netframework
            build-dir: net48
          - platform: net-x86
            package-name: net-win32
            build-dir: net8.0-windows\win-x86\publish
          - platform: net-x64
            package-name: net-win64
            build-dir: net8.0-windows\win-x64\publish

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          submodules: true
      - uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: 8.0.x
          dotnet-quality: ga
      - uses: microsoft/setup-msbuild@v2.0.0
      
     - name: 创建输出目录
        run: |
          New-Item -ItemType Directory -Force -Path "C:\builtfiles"

      # 修改构建步骤，确保文件输出到正确位置
      - name: Build ${{matrix.platform}}
        run: |
          if ('${{matrix.platform}}' -eq 'netframework') {
            msbuild dnSpy.sln /m /r /p:Configuration=Release /p:Platform="Any CPU" /p:OutDir="C:\builtfiles\dnSpy-${{matrix.platform}}\"
          } else {
            dotnet publish dnSpy.sln -c Release -f net8.0-windows --self-contained true -r win-${{matrix.platform == 'net-x86' && 'x86' || 'x64'}} -o "C:\builtfiles\dnSpy-${{matrix.platform}}"
          }

      # 验证文件是否存在
      - name: 验证构建输出
        run: |
          if (!(Test-Path "C:\builtfiles\dnSpy-${{matrix.platform}}")) {
            Write-Error "构建输出目录不存在"
            exit 1
          }
          Get-ChildItem "C:\builtfiles\dnSpy-${{matrix.platform}}" -Recurse

      - uses: actions/upload-artifact@v4.4.3
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
        with:
          name: dnSpy-${{matrix.package-name}}
          path: C:\builtfiles\dnSpy-${{matrix.platform}}
          if-no-files-found: error
          compression-level: 9
